"""Shared configuration for the Gomoku app."""

BOARD_SIZE = 15
CELL_SIZE = 40
MARGIN = 40
INFO_HEIGHT = 190

MODE_LOCAL_2P = "local_2p"
MODE_VS_AI = "vs_ai"
DEFAULT_MODE = MODE_LOCAL_2P
VALID_MODES = (MODE_LOCAL_2P, MODE_VS_AI)

AI_DIFFICULTY_SIMPLE = "simple"
AI_DIFFICULTY_NORMAL = "normal"
AI_DIFFICULTY_HARD = "hard"
AI_DIFFICULTIES = (
    AI_DIFFICULTY_SIMPLE,
    AI_DIFFICULTY_NORMAL,
    AI_DIFFICULTY_HARD,
)

WINDOW_WIDTH = MARGIN * 2 + CELL_SIZE * (BOARD_SIZE - 1)
WINDOW_HEIGHT = WINDOW_WIDTH + INFO_HEIGHT

STONE_RADIUS = 16
FPS = 60

BACKGROUND_COLOR = (224, 176, 102)
LINE_COLOR = (54, 38, 22)
BLACK_COLOR = (24, 24, 24)
WHITE_COLOR = (245, 242, 235)
TEXT_COLOR = (30, 30, 30)
WIN_COLOR = (156, 44, 38)
LAST_MOVE_COLOR = (210, 52, 48)
