"""Shared configuration for the Gomoku app."""

import os

APP_VERSION = "0.3.3"
BOARD_SIZE = 15
CELL_SIZE = 40
MARGIN = 40
INFO_HEIGHT = 190

MODE_LOCAL_2P = "local_2p"
MODE_VS_AI = "vs_ai"
DEFAULT_MODE = MODE_LOCAL_2P
VALID_MODES = (MODE_LOCAL_2P, MODE_VS_AI)

AI_DIFFICULTY_SIMPLE = "simple"
AI_DIFFICULTY_NORMAL = "normal"
AI_DIFFICULTY_HARD = "hard"
AI_DIFFICULTIES = (
    AI_DIFFICULTY_SIMPLE,
    AI_DIFFICULTY_NORMAL,
    AI_DIFFICULTY_HARD,
)
DEFAULT_AI_DIFFICULTY = AI_DIFFICULTY_SIMPLE
AVAILABLE_AI_DIFFICULTIES = (
    AI_DIFFICULTY_SIMPLE,
    AI_DIFFICULTY_NORMAL,
)

PUBLIC_BASE_URL = os.getenv("GOMOKU_PUBLIC_BASE_URL", "").rstrip("/")
ROOM_TTL_SECONDS = int(os.getenv("GOMOKU_ROOM_TTL_SECONDS", str(12 * 60 * 60)))
ROOM_CLEANUP_INTERVAL_SECONDS = int(
    os.getenv("GOMOKU_ROOM_CLEANUP_INTERVAL_SECONDS", str(5 * 60))
)
ROOM_CREATE_LIMIT = int(os.getenv("GOMOKU_ROOM_CREATE_LIMIT", "5"))
ROOM_CREATE_WINDOW_SECONDS = int(
    os.getenv("GOMOKU_ROOM_CREATE_WINDOW_SECONDS", str(10 * 60))
)
MAX_ACTIVE_ROOMS = int(os.getenv("GOMOKU_MAX_ACTIVE_ROOMS", "100"))
MAX_LOCAL_GAME_SESSIONS = int(os.getenv("GOMOKU_MAX_LOCAL_GAME_SESSIONS", "128"))
LOCAL_GAME_SESSION_TTL_SECONDS = int(
    os.getenv("GOMOKU_LOCAL_GAME_SESSION_TTL_SECONDS", str(12 * 60 * 60))
)
ROOM_AUTH_TIMEOUT_SECONDS = int(os.getenv("GOMOKU_ROOM_AUTH_TIMEOUT_SECONDS", "10"))
ENABLE_API_DOCS = os.getenv("GOMOKU_ENABLE_API_DOCS", "").lower() in {
    "1",
    "true",
    "yes",
}

WINDOW_WIDTH = MARGIN * 2 + CELL_SIZE * (BOARD_SIZE - 1)
WINDOW_HEIGHT = WINDOW_WIDTH + INFO_HEIGHT

STONE_RADIUS = 16
FPS = 60

BACKGROUND_COLOR = (224, 176, 102)
LINE_COLOR = (54, 38, 22)
BLACK_COLOR = (24, 24, 24)
WHITE_COLOR = (245, 242, 235)
TEXT_COLOR = (30, 30, 30)
WIN_COLOR = (156, 44, 38)
LAST_MOVE_COLOR = (210, 52, 48)
